services:
  #----------------------------------------------------------------------------#
  #                                 CLIENT                                     #
  #----------------------------------------------------------------------------#
  client:
    container_name: client
    image: client
    build:
      context: services/client/
    volumes:
      - client_volume:/var/npm-project
      - node_modules_client:/var/npm-project/node_modules
      - www:/var/www
    restart: "always"
  
  #----------------------------------------------------------------------------#
  #                                  SERVER                                    #
  #----------------------------------------------------------------------------#
  server:
    container_name: server
    image: server
    build:
      context: services/server/
    volumes:
      - server_volume:/var/npm-project
      - node_modules_server:/var/npm-project/node_modules
      - www:/var/www
    networks:
      - trancendence
    restart: "always"

  #----------------------------------------------------------------------------#
  #                                   NGINX                                    #
  #----------------------------------------------------------------------------#
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: services/nginx/
    ports:
      - 8080:8080
    networks:
      - trancendence
    restart: "always"
  #----------------------------------------------------------------------------#
  #                                    VOLUMES                                 #
  #----------------------------------------------------------------------------#

volumes:
  client_volume:
    name: client_volume
    driver: local
    driver_opts:
      device: ./services/client/npm-project
      o: bind
      type: none
  server_volume:
    name: server_volume
    driver: local
    driver_opts:
      device: ./services/server/npm-project
      o: bind
      type: none
  www:
    name: www
    driver: local
    driver_opts:
      device: ./built_data/www
      o: bind
      type: none
  node_modules_client:
  node_modules_server:

networks:
  rooms:
    name: rooms
    driver: bridge
